using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LazyGenerator;

[Generator]
internal sealed class LazyGenerator : IIncrementalGenerator
{
    private static DiagnosticDescriptor RegexMemberMustHaveValidSignature { get; } = new(
        id: "LAZY0",
        title: "Invalid LazyAttribute usage",
        messageFormat: "LazyAttribute property must be partial and non-abstract",
        category: "LazyGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        customTags: WellKnownDiagnosticTags.NotConfigurable
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
        {
            postInitializationContext.AddEmbeddedAttributeDefinition();
            postInitializationContext.AddSource(
                "LazyAttribute.g.cs",
                """
                // <auto-generated />
                #nullable enable
                namespace AsmResolver;

                [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                internal sealed class LazyAttribute : global::System.Attribute
                {
                    public LazyAttribute(string factoryMethod) {}
                }
                """);
        });

        var results = context.SyntaxProvider
            .ForAttributeWithMetadataName<object?>(
                fullyQualifiedMetadataName: "AsmResolver.LazyAttribute",
                predicate: static (syntaxNode, _) => syntaxNode is PropertyDeclarationSyntax,
                transform: static (context, _) =>
                {
                    var factoryMethodName = context.Attributes.SingleOrDefault()?.ConstructorArguments.SingleOrDefault().Value as string;
                    if (factoryMethodName == null)
                    {
                        return null;
                    }

                    var syntax = (PropertyDeclarationSyntax) context.TargetNode;
                    var symbol = (IPropertySymbol) context.TargetSymbol;

                    if (!symbol.IsPartialDefinition || symbol.IsAbstract || symbol.GetMethod == null)
                    {
                        return new DiagnosticData(RegexMemberMustHaveValidSignature, GetComparableLocation(syntax));
                    }

                    var containingType = symbol.ContainingType;

                    var @namespace = containingType?.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

                    var parentsBuilder = ImmutableArray.CreateBuilder<(string Keyword, string Name)>();

                    var parent = syntax.Parent as TypeDeclarationSyntax;
                    while (parent is not null && IsAllowedKind(parent.Kind()))
                    {
                        parentsBuilder.Add((GetTypeKeyword(parent), GetTypeIdentifier(parent)));
                        parent = parent.Parent as TypeDeclarationSyntax;
                    }

                    return new Model(
                        @namespace,
                        parentsBuilder.DrainToImmutable(),
                        syntax.Modifiers.ToString(),
                        symbol.Type.ToDisplayString(),
                        symbol.Type.IsValueType || symbol.Type.NullableAnnotation == NullableAnnotation.Annotated,
                        symbol.Name,
                        symbol.SetMethod != null,
                        factoryMethodName
                    );

                    static string GetTypeKeyword(TypeDeclarationSyntax type)
                    {
                        return type is RecordDeclarationSyntax rds ? $"{type.Keyword.ValueText} {rds.ClassOrStructKeyword}" : type.Keyword.ValueText;
                    }

                    static string GetTypeIdentifier(TypeDeclarationSyntax type)
                    {
                        return $"{type.Identifier}{type.TypeParameterList}";
                    }

                    static bool IsAllowedKind(SyntaxKind kind) => kind is
                        SyntaxKind.ClassDeclaration or
                        SyntaxKind.StructDeclaration or
                        SyntaxKind.RecordDeclaration or
                        SyntaxKind.RecordStructDeclaration or
                        SyntaxKind.InterfaceDeclaration;
                }
            )
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            results,
            static (context, modelOrDiagnostic) =>
            {
                if (modelOrDiagnostic is DiagnosticData diagnostic)
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                    return;
                }

                var model = (Model) modelOrDiagnostic!;

                using StringWriter sw = new();
                using IndentedTextWriter writer = new(sw);

                writer.WriteLine("// <auto-generated />");
                writer.WriteLine("#nullable enable");
                writer.WriteLine();

                EmitLazyPartialProperty(model, writer);

                context.AddSource(
                    $"{model.Parents.First().Name}_{model.Name}.g.cs",
                    sw.ToString()
                );
            }
        );
    }

    private static void EmitLazyPartialProperty(Model model, IndentedTextWriter writer)
    {
        var fieldName = "_" +
                        char.ToLowerInvariant(model.Name[0]) +
                        model.Name[1..];
        var initializedFieldName = fieldName + "Initialized";

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        foreach (var parent in model.Parents)
        {
            writer.WriteLine($"partial {parent.Keyword} {parent.Name}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        if (model.IsValueTypeOrNullable)
        {
            writer.WriteLine($"private {model.Type} {fieldName};");
            writer.WriteLine($"private bool {initializedFieldName};");
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"private {model.Type}? {fieldName};");
            writer.WriteLine();
        }

        writer.WriteLine($"{model.Modifiers} {model.Type} {model.Name}");

        writer.WriteLine("{");
        writer.Indent++;

        if (model.IsValueTypeOrNullable)
        {
            writer.WriteLines(
                $$"""
                  get
                  {
                      if (System.Threading.Volatile.Read(ref {{initializedFieldName}}))
                      {
                          return {{fieldName}};
                      }

                      lock (_lock)
                      {
                          if (!System.Threading.Volatile.Read(ref {{initializedFieldName}}))
                          {
                              {{fieldName}} = {{model.FactoryMethodName}}();
                              System.Threading.Volatile.Write(ref {{initializedFieldName}}, true);
                          }
                      }

                      return {{fieldName}};
                  }
                  """
            );

            if (model.HasSetter)
            {
                writer.WriteLine();
                writer.WriteLines(
                    $$"""
                      set
                      {
                          lock (_lock)
                          {
                              {{fieldName}} = value;
                              {{initializedFieldName}} = true;
                          }
                      }
                      """
                );
            }
        }
        else
        {
            writer.WriteLines(
                $$"""
                  get
                  {
                      if ({{fieldName}} is null) System.Threading.Interlocked.CompareExchange(ref {{fieldName}}, {{model.FactoryMethodName}}(), null);
                      return {{fieldName}};
                  }
                  """
            );

            if (model.HasSetter)
            {
                writer.WriteLine();
                writer.WriteLine($"set => {fieldName} = value;");
            }
        }

        while (writer.Indent != 0)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    private record Model(
        string? Namespace,
        ImmutableArray<(string Keyword, string Name)> Parents,
        string Modifiers,
        string Type,
        bool IsValueTypeOrNullable,
        string Name,
        bool HasSetter,
        string FactoryMethodName
    );

    private sealed record DiagnosticData(DiagnosticDescriptor Descriptor, Location Location /*, params object?[]? MessageArgs*/)
    {
        public Diagnostic ToDiagnostic() => Diagnostic.Create(Descriptor, Location /*, MessageArgs*/);
    }

    private static Location GetComparableLocation(SyntaxNode syntax)
    {
        var location = syntax.GetLocation();
        return Location.Create(location.SourceTree?.FilePath ?? string.Empty, location.SourceSpan, location.GetLineSpan().Span);
    }
}

internal static class Extensions
{
    public static void WriteLines(this IndentedTextWriter writer, string lines)
    {
        foreach (var line in lines.Split(["\r\n", "\r", "\n"], StringSplitOptions.None))
        {
            writer.WriteLine(line);
        }
    }

    public static void AddEmbeddedAttributeDefinition(this IncrementalGeneratorPostInitializationContext context)
    {
        var text =
            """
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }
            """;

        context.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute", SourceText.From(text, encoding: Encoding.UTF8));
    }
}
